# Generated by Django 3.2.23 on 2023-12-18 09:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('caps', 'Caps'), ('tshirts', 'T-Shirts')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.category')),
                ('main_colour', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=50, verbose_name='Main colour')),
                ('second_colour', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=50, verbose_name='Secondary colour')),
                ('logo_colour', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=50, null=True, verbose_name='Logo colour')),
                ('brand', models.CharField(max_length=200, verbose_name='Brand')),
                ('inclusion_date', models.DateTimeField(auto_now_add=True, verbose_name='Date first inclusion')),
                ('url_img', models.URLField(max_length=500, verbose_name='URL Image')),
                ('price', models.FloatField(verbose_name='Price')),
                ('initial_stock', models.IntegerField(default=10, editable=False, verbose_name='Initial Stock')),
                ('current_stock', models.IntegerField(verbose_name='Current Stock')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('size', models.CharField(blank=True, choices=[('extra_small', 'Extra Small'), ('small', 'Small'), ('medium', 'Medium'), ('medium', 'Large'), ('extra_large', 'Extra Large')], max_length=200, null=True, verbose_name='Size')),
                ('sizing', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=200, null=True, verbose_name='Sizing')),
                ('fabric', models.CharField(blank=True, choices=[('cottom', 'Cottom'), ('lycra', 'Lycra'), ('polyester', 'Polyester')], max_length=50, null=True, verbose_name='Fabric')),
                ('sleeve', models.BooleanField(blank=True, default=True, null=True, verbose_name='Sleeve')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_cart', to='store.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='store.product')),
            ],
        ),
    ]
